# Generated by Django 4.2 on 2023-05-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
