# Generated by Django 4.2 on 2023-05-21 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_customuser_bookreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
